# Generated by Django 4.0.6 on 2022-07-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('phone_no', models.IntegerField()),
                ('gender', models.CharField(max_length=16)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
