# Generated by Django 4.0.6 on 2022-07-14 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
